# Generated by Django 5.2.5 on 2025-11-26 22:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radio_permitido', models.IntegerField(default=50, help_text='Metros permitidos para marcar')),
                ('presupuesto_total', models.DecimalField(decimal_places=0, max_digits=15)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino_estimada', models.DateField()),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('total_pagado_sueldos', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('total_perdido_improductivo', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('presupuesto_restante', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('es_rentable', models.BooleanField(default=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.obra')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('JEFE', 'Jefe de Obra'), ('TRABAJADOR', 'Trabajador')], default='TRABAJADOR', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('sueldo_diario', models.DecimalField(decimal_places=0, default=0, help_text='Costo diario del trabajador para la empresa', max_digits=10)),
                ('valor_hora', models.DecimalField(decimal_places=0, default=0, help_text='Para calcular pérdidas por horas improductivas', max_digits=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='obra',
            name='jefe_obra',
            field=models.ForeignKey(limit_choices_to={'rol': 'JEFE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro.perfil'),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora_entrada', models.TimeField(auto_now_add=True)),
                ('latitud_entrada', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud_entrada', models.DecimalField(decimal_places=6, max_digits=9)),
                ('foto_entrada', models.ImageField(blank=True, null=True, upload_to='asistencias/entrada/')),
                ('entrada_valida', models.BooleanField(default=False)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('latitud_salida', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud_salida', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('foto_salida', models.ImageField(blank=True, null=True, upload_to='asistencias/salida/')),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('monto_pago_dia', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.obra')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteImproductivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('motivo', models.TextField(help_text='Ej: Constructora no liberó losas, falta de grúa, etc.')),
                ('evidencia_foto', models.ImageField(blank=True, null=True, upload_to='evidencias_perdida/')),
                ('horas_perdidas_totales', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('dinero_perdido', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('jefe_obra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_creados', to='registro.perfil')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.obra')),
                ('trabajadores_afectados', models.ManyToManyField(limit_choices_to={'rol': 'TRABAJADOR'}, to='registro.perfil')),
            ],
        ),
    ]
