# Generated by Django 5.2.5 on 2025-12-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='radio_permitido',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='sueldo_diario',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='valor_hora',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reporteimproductivo',
            name='motivo',
            field=models.TextField(),
        ),
    ]
