# Generated by Django 5.2.5 on 2025-12-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_alter_obra_radio_permitido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteimproductivo',
            name='leido',
            field=models.BooleanField(default=False, verbose_name='¿Leído por Admin?'),
        ),
    ]
