# Generated by Django 5.2.5 on 2025-12-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_reporteimproductivo_leido'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceobra',
            name='total_multas_proyectadas',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='obra',
            name='valor_multa_dia',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Multa por día de atraso según contrato', max_digits=10),
        ),
        migrations.AddField(
            model_name='reporteimproductivo',
            name='dias_retraso_obra',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Días que se atrasa la entrega final por este incidente', max_digits=4),
        ),
    ]
