# Generated by Django 5.2.5 on 2025-12-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_balanceobra_total_multas_proyectadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='ip_registro',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='dispositivo_id',
            field=models.CharField(blank=True, help_text='ID único del celular vinculado', max_length=100, null=True),
        ),
    ]
