# Generated by Django 5.2.5 on 2025-12-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_asistencia_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='latitud_entrada',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='latitud_salida',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='longitud_entrada',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='longitud_salida',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='obra',
            name='latitud',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='obra',
            name='longitud',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
